name:                servant-oauth-sample
version:             0.1.0.0
github:              "githubuser/servant-oauth-sample"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-oauth-sample#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- containers
- time
- directory
- safe-exceptions
- warp
- servant
- servant-server
- servant-client
- servant-auth
- servant-auth-server
- servant-lucid
- lucid
- sqlite-simple
- aeson
- mtl
- lens
- http-api-data
- http-media
- http-client
- hspec

library:
  source-dirs: src

executables:
  servant-oauth-sample-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-oauth-sample

tests:
  servant-oauth-sample-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-oauth-sample
